#####################################################################################################
# Copyright Notice
# All Rights Reserved.
# All course materials (the “Materials”) are protected by copyright under U.S. Copyright laws 
# and are the property of 2nd Sight Lab. They are provided pursuant to a royalty free, 
# perpetual license to the course attendee (the "Attendee") to whom they were presented by 
# 2nd Sight Lab and are solely for the training and education of the Attendee. The Materials 
# may not be copied, reproduced, distributed, offered for sale, published, displayed, performed, 
# modified, used to create derivative works, transmitted to others, or used or exploited in any way, 
# including, in whole or in part, as training materials by or for any third party.

# The above copyright notice and this permission notice shall be included in all copies or 
# substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES 
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#####################################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: 3-NACLs

Parameters:
  Username:
    Description: Your username for tagging resources.
    Type: String
    Default: username

Resources:
  # ------------------------------------------------
  # Public NACL
  # ------------------------------------------------
  PublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue "Lab-2-1-VPCID"
      Tags:
      - Key: Name
        Value: !Sub 
          - ${VPCName}-Public-NACL
          - VPCName: !ImportValue Lab-2-1-VPCName
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !ImportValue Lab-2-1-VPCName
      - Key: Created_By
        Value: !Sub ${Username}

  PublicNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue "Lab-2-1-Public-Subnet"
      NetworkAclId: !Ref PublicNACL

  PublicNACLInbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: !Select [ 1, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]
  PublicNACLInbound101Deny:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "101"
      Protocol: "6"
      PortRange:
        From: "0"
        To: "65535"
      RuleAction: Deny
      Egress: "false"
      CidrBlock: !ImportValue "Lab-2-1-VPCCidr"
  PublicNACLInbound102Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "102"
      Protocol: "6"
      PortRange:
        From: "80"
        To: "80"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound103Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "103"
      Protocol: "6"
      PortRange:
        From: "443"
        To: "443"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0

  PublicNACLOutbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "8080"
        To: "8080"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !Select [ 1, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]
  PublicNACLOutbound101Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "101"
      Protocol: "17"
      PortRange:
        From: "53"
        To: "53"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !ImportValue "Lab-2-1-DNSCidr"
  PublicNACLOutbound102Deny:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "102"
      Protocol: "6"
      PortRange:
        From: "0"
        To: "65535"
      RuleAction: Deny
      Egress: "true"
      CidrBlock: !ImportValue "Lab-2-1-VPCCidr"
  PublicNACLOutbound103Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${PublicNACL}
      RuleNumber: "103"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0

  # ------------------------------------------------
  # Application NACL
  # ------------------------------------------------
  ApplicationNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue "Lab-2-1-VPCID"
      Tags:
      - Key: Name
        Value: !Sub 
          - ${VPCName}-Application-NACL
          - VPCName: !ImportValue Lab-2-1-VPCName
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !ImportValue Lab-2-1-VPCName
      - Key: Created_By
        Value: !Sub ${Username}

  ApplicationNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue "Lab-2-1-Application-Subnet"
      NetworkAclId: !Ref ApplicationNACL

  ApplicationNACLInbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${ApplicationNACL}
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "8080"
        To: "8080"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: !Select [ 0, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]
  ApplicationNACLInbound101Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${ApplicationNACL}
      RuleNumber: "101"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: !Select [ 2, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]

  ApplicationNACLOutbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${ApplicationNACL}
      RuleNumber: "100"
      Protocol: "17"
      PortRange:
        From: "53"
        To: "53"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !ImportValue "Lab-2-1-DNSCidr"
  ApplicationNACLOutbound101Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${ApplicationNACL}
      RuleNumber: "101"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !Select [ 0, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]
  ApplicationNACLOutbound102Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${ApplicationNACL}
      RuleNumber: "102"
      Protocol: "6"
      PortRange:
        From: "3306"
        To: "3306"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !Select [ 2, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]


  # ------------------------------------------------
  # Database NACL
  # ------------------------------------------------
  DatabaseNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue "Lab-2-1-VPCID"
      Tags:
      - Key: Name
        Value: !Sub 
          - ${VPCName}-Database-NACL
          - VPCName: !ImportValue Lab-2-1-VPCName
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !ImportValue Lab-2-1-VPCName
      - Key: Created_By
        Value: !Sub ${Username}

  DatabaseNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !ImportValue "Lab-2-1-Database-Subnet"
      NetworkAclId: !Ref DatabaseNACL

  DatabasenNACLInbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${DatabaseNACL}
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "3306"
        To: "3306"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: !Select [ 1, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]

  DatbaseNACLOutbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${DatabaseNACL}
      RuleNumber: "100"
      Protocol: "17"
      PortRange:
        From: "53"
        To: "53"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !ImportValue "Lab-2-1-DNSCidr"
  DatabaseNACLOutbound101Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Sub ${DatabaseNACL}
      RuleNumber: "101"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !Select [ 1, !Cidr [ !ImportValue "Lab-2-1-VPCCidr", 16, 8 ] ]
