#!/bin/bash -e
################################################################
#
#  Name: Launch_instance
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/functions/launch_instance.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


launch_instance(){
  local ami_id="$1"
  local key_pair_name="$2"
  local security_group_id="$3"
  local subnet_id="$4"
  local kms_key="$5"
  local archive_to="$6"
  local region="$7"
  local instance_size="$8"

   local instance_id=$(aws ec2 run-instances --image-id "$ami_id" \
    --instance-type "$instance_size" --key-name "$key_pair_name" \
    --security-group-ids "$security_group_id" \
    --subnet-id "$subnet_id" \
    --block-device-mappings "$block_device_mappings" \
    --query "Instances[0].InstanceId" \
    --output text \
    --region $region \
    --profile "$archive_to" \
    --color off 2>&1)
 
  echo "$instance_id"

}
