#!/bin/bash -e
################################################################
#
#  Name: Share_ami
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/functions/share_ami.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


share_ami(){
  local AMI_ID="$1"
  local to_account="$2"
  local archive_from="$3"
  local region="$4"

  echo "Share ami: $AMI_ID"
  
  aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId=$to_account}]" \
           --profile $archive_from --region $region --color off
  echo "Shared the AMI."
  echo "Status is pending...."
}
