#!/bin/bash -e
################################################################
#
#  Name: Colors_bash
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/deploy-ec2-instance/user_data_scripts/colors_bash.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################

if grep -q "export NO_COLOR=true" "$HOME/.bashrc"; then
  echo "Color settings (NO_COLOR=true) already detected. Exiting script."
  exit 0
fi

sudo -u ec2-user bash << "EOF"

THIS_DIR="$(pwd)"
cd /home/ec2-user
# run this before installing Amazon Q"
echo ''  >> ~/.bashrc
echo '#remove docker color madness' >> ~/.bashrc
echo "export NO_COLOR=true" >> ~/.bashrc

echo ''  >> ~/.bashrc
echo '#set background color' >> ~/.bashrc
echo '#https://htmlcolorcodes.com/color-picker/' >> ~/.bashrc
echo '#this does not work on mac if you are using defulat zsh terminal app.' >> ~/.bashrc
echo '#should work in bash' >> ~/.bashrc
echo '#you can change to bash with this command:' >> ~/.bashrc
echo '#chsh -s /bin/bash' >> ~/.bashrc
echo '#Mac uses zsh due to licensing issues and it has some different features' >> ~/.bashrc
echo 'echo -e "\e]11;#021621\a"' >> ~/.bashrc
echo ''  >> ~/.bashrc
echo '#PS1'  >> ~/.bashrc
echo '#The first item is the prompt' >> ~/.bashrc
echo '#The terminal emulator looks for output containing that specific code (\e]0;) and uses everything up to the \a as the terminal window title.' >> ~/.bashrc
echo 'export PS1=":^) \e]0;2nd Sight Lab\a"' >> ~/.bashrc
echo ''  >> ~/.bashrc
echo "#white please..." >> ~/.bashrc
echo 'LS_COLORS="di=1;37:ex=1;37:fi=1;37:ln=1;37:pi=1;37:so=1;37:bd=1;37:cd=1;37:or=1;37:mi=1;37"' >> ~/.bashrc

echo ''  >> ~/.bashrc
echo "#But that is not working anymore so:" >> ~/.bashrc
echo "export NO_COLOR=1" >> ~/.bashrc
echo "alias ls='ls --color=never'" >> ~/.bashrc
echo "alias grep='grep --color=never'" >> ~/.bashrc
echo "alias diff='diff --color=never'" >> ~/.bashrc
echo "alias aws='aws --color off'" >> ~/.bashrc
echo "alias git='git -c color.ui=never'" >> ~/.bashrc
echo "#If you installed Amazon Q make sure that line is at the bottom of bashrc" >> ~/.bashrc

echo "all font should be white. If it is not trying executing source ~/.bashrc again."

cd "$THIS_DIR"

EOF
