#!/bin/bash -e
################################################################
#
#  Name: Disable_ipv6
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/deploy-ec2-instance/user_data_scripts/disable_ipv6.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




# Detect OS and disable IPv6
if [ -f /etc/redhat-release ] || [ -f /etc/amazon-linux-release ]|| grep -q "Amazon Linux 2" /etc/os-release; then
    # RHEL/CentOS/Amazon Linux
    sudo grubby --update-kernel=ALL --args="ipv6.disable=1"
elif [ -f /etc/debian_version ]; then
    # Debian/Ubuntu
    sudo sh -c 'echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf'
    sudo sh -c 'echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf'
    sudo echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash ipv6.disable=1\"" >> /etc/default/grub
    sudo echo "GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"" >> /etc/default/grub
    sysctl -p
elif [ -f /etc/SuSE-release ]; then
    # SUSE
    sudo sh -c 'echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf'
    sudo sh -c 'echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf'
    sysctl -p
else
    echo "Unsupported OS for IPv6 disable"
    exit 1
fi
