#!/bin/bash -e
################################################################
#
#  Name: Install_amazon_q
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/deploy-ec2-instance/user_data_scripts/install_amazon_q.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


sudo -u ec2-user bash << 'EOF'

DOWNLOAD_FILE="q.zip"
VERSION=""
ARCH=""
DOWNLOAD_URL=""
OS=""
VERSION_ID=""
THIS_DIR=$(pwd)

cd /home/ec2-user

if ! ldd --version 2>&1 | head -n 1 | grep -q 'GLIBC 2.3[4-9]'; then
    VERSION="-musl"
fi

case "$(uname -m)" in
    x86_64) ARCH="x86_64-linux" ;;
    aarch64) ARCH="aarch64-linux" ;;
    *) echo "Unsupported architecture." >&2; exit 1 ;;
esac

DOWNLOAD_URL="https://desktop-release.q.us-east-1.amazonaws.com/latest/q-${ARCH}${VERSION}.zip"

if ! command -v curl &> /dev/null; then
 echo "Curl is not installed"; exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    echo "Cannot detect OS"
    exit 1
fi

# Install Amazon Q based on OS
case $OS in
        "ubuntu"|"amzn"|"rhel"|"centos")
        if ! curl -sSL --tlsv1.2 --proto '=https' $DOWNLOAD_URL -o $DOWNLOAD_FILE; then
           echo "Error: Download failed for $DOWNLOAD_URL" >&2
           return 1
        fi

        if [ ! -s "$DOWNLOAD_FILE" ]; then
          echo "Error: Downloaded file is empty or missing." >&2
          # Optional: remove the empty file
          rm -f "$DOWNLOAD_FILE"
          return 1
        fi

        echo "Successfully downloaded $DONWLOAD_FILE"

        echo "Files in tmp:"
        ls -al

        echo "Check file:"
        file $DOWNLOAD_FILE

        echo "Unzip file"
        unzip $DOWNLOAD_FILE

        echo "Install /q/install.sh"
        ./q/install.sh --no-confirm
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

cd $THIS_DIR
EOF

q --version || echo "Cannot check version of Amazon Q. May not be installed or need to login."
