#!/bin/bash -e
################################################################
#
#  Name: Update
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/deploy-ec2-instance/user_data_scripts/update.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




# Update and upgrade system packages based on OS
if [ -f /etc/redhat-release ] || [ -f /etc/amazon-linux-release ] || grep -q "Amazon Linux 2" /etc/os-release; then
    # RHEL/CentOS/Amazon Linux
    sudo yum update -y
elif [ -f /etc/debian_version ]; then
    # Debian/Ubuntu
    sudo apt-get update -y
    sudo apt-get upgrade -y
elif [ -f /etc/SuSE-release ]; then
    # SUSE
    sudo zypper refresh
    sudo zypper update -y
else
    echo "Unsupported OS for package updates"
    exit 1
fi
