#!/bin/bash -e
################################################################
#
#  Name: Run
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/select-region/run.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../select-aws-cli-profile/run.sh"
source "$SCRIPT_DIR/../../functions/list_regions.sh"

REGIONS=($(list_regions "$PROFILE"))

if [ ${#REGIONS[@]} -eq 0 ]; then
    echo "No regions found."
    exit 1
fi

echo "Available AWS regions:"
for I in "${!REGIONS[@]}"; do
    echo "$((I+1)). ${REGIONS[I]}"
done

while true; do
    read -p "Enter region number (1-${#REGIONS[@]}): " CHOICE
    if [[ "$CHOICE" =~ ^[0-9]+$ ]] && [ "$CHOICE" -ge 1 ] && [ "$CHOICE" -le ${#REGIONS[@]} ]; then
        REGION="${REGIONS[$((CHOICE-1))]}"
        echo "Selected region: $REGION"
        break
    else
        echo "Invalid selection. Please enter a number between 1 and ${#REGIONS[@]}."
    fi
done
