AWSTemplateFormatVersion: "2010-09-09"
Description: "Base S3 Bucket - Policy"

Resources:
  BaseS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue "lab-3-3-bucket-name"
      PolicyDocument:
        Statement:
          -
            Sid: DenyUnEncryptedObject1
            Action: s3:PutObject
            Effect: Deny
            Principal:
              "AWS": "*"
            Resource: !Sub 
              - "arn:aws:s3:::${bucket_name}/*"
              - bucket_name: !ImportValue "lab-3-3-bucket-name"
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption":
                  "aws:kms"
          -
            Sid: DenyUnEncryptedObject2
            Action: s3:PutObject
            Effect: Deny
            Principal: "*"
            Resource: !Sub 
              - "arn:aws:s3:::${bucket_name}/*"
              - bucket_name: !ImportValue "lab-3-3-bucket-name"
            Condition:
              "Null":
                "s3:x-amz-server-side-encryption": "true"
