AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaEdgeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AuthLambda@Edge
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
              - edgelambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AuthLambda@Edge
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource: 
                  - arn:aws:ssm:us-west-2:306115006586:parameter/*
                  - arn:aws:ssm:us-east-1:306115006586:parameter/*
                  - arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: 
                  - arn:aws:logs:*:*:*
