#!/bin/bash -e
################################################################
#
#  Name: Ec2 Keys
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/ec2-keys.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



cat <<'END_TEXT'

***************************
SSH KEY Pairs
***************************

END_TEXT

echo "Here are a list of the EC2 SSH keys:"
echo ""
aws ec2 describe-key-pairs --profile $archive_from region $region
echo ""
echo "Add the values of EC2 keys to Secrets Manager before archiving secrets"
echo "if you want to retain the value of the key pairs. Note that you will"
echo "have to obtain the private key from wherever it is stored. Also"
echo "this command does not take into account key pairs created outside"
echo "the AWS EC2 console."
echo ""
echo "Enter to continue. Ctrl-C to exit."
