#!/bin/bash -e
################################################################
#
#  Name: Archive EIPs
#  GitHub repository: https://github.com/2ndSightLab
#  File: eips.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Archive Elastic IP addresses
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


cat <<'END_TEXT'

***************************
Elastic IP Addresses (EIPs)
***************************
END_TEXT

read -p "Do you want to copy any EIPs? " copy

if [ "$copy" == "y" ]; then 

cat <<'END_TEXT'

You might want a record of the EIPs that may exist in
logs or have been used in firewall rules, DNS records,
or other configurations. Here is a list of the EIPs 
in this account: 

END_TEXT

aws ec2 describe-addresses --profile $archive_from --region $region \
  --query 'Addresses[*].{Name:Tags[?Key==`Name`].Value | [0], PublicIp:PublicIp}' --output text

read -p "If you want a record of the EIPs copy to a secret or parameter. Enter to continue. Ctrl-C to exit)" ok

fi #end if copy
copy=""
