#!/bin/bash -e
################################################################
#
#  Name: Iam Roles
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/iam-roles.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




cat <<'END_TEXT'

***************************
IAM Roles 
***************************

You may want a record of the IAM role names in this account
in case they appear in any logs or you need to replicate
them again later. Here are a list of the IAM oroles in this account:

END_TEXT

aws iam list-roles --profile $ARCHIVE_FROM --region $REGION \
  --query 'Roles[?starts_with(Path, `/`) && !starts_with(Path, `/aws-service-role/`) && !starts_with(Path, `/aws-reserved/sso/`)].RoleName' \
  --output text \
| xargs -n 1

echo ""

read -p "Copy the names of the roles into a parameter or secret if needed. \
  Enter to continue. Ctrl-C to exit" OK
