#!/bin/bash -e
################################################################
#
#  Name: Iam Policies
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/iam-policies.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




cat <<'END_TEXT'

***************************
IAM Roles 
***************************

You can transfer some or all of the policies in this account
to the new account but note that the principals have to exist
and if deleted, will be turned into an unusable logical ID.
Instead, if you plan to use the policies in the future, 
recreate them in the new archive account using users or roles
in the archive account if needed, or store the policies
in an SSM parameter for future reference.

END_TEXT

aws iam list-policies --profile $ARCHIVE_FROM --region $REGION \
  --scope Local \
  --query "Policies[].PolicyName" \
  --output text \
  | xargs -n 1

read -p "Copy or recreate the above policies as needed. Ctrl-C to exit" OK
