#!/bin/bash -e
################################################################
#
#  Name: Parameters
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/parameters.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




archive_parameter(){
 local FROM_PARAMETER="$1"
 local TO_PARAMETER="$2"
 local ARCHIVE_FROM="$3"
 local ARCHIVE_TO="$4"
 local REGION="$5"
 local KMS_KEY_ID="$6"

 local PARAMETER_VALUE=""

 PARAMETER_VALUE=$(aws ssm get-parameter \
    --profile "$ARCHIVE_FROM" \
    --region "$REGION" \
    --name "$FROM_PARAMETER" \
    --with-decryption \
    --query 'Parameter.Value' \
    --output text)
   
    if [ -z "$PARAMETER_VALUE" ]; then
        echo "Error: Parameter value could not be retrieved or is empty."
        echo "Does the AWS CLI Profile: $ARCHIVE_FROM have permission to decrypt the parameter?"
        exit 1
    fi

    aws ssm put-parameter \
    --profile "$ARCHIVE_TO" \
    --region "$REGION" \
    --name "$TO_PARAMETER" \
    --value "$PARAMETER_VALUE" \
    --key-id "$KMS_KEY_ID" \
    --overwrite \
    --type "SecureString"

    if [ $? -ne 0 ]; then
      echo "Error: Failed to create parameter $TO_PARAMETER"
      exit 1
    fi

    PARAMETER_VALUE=""
}

cat <<'END_TEXT'

***************************
SSM Secrets
***************************

END_TEXT

read -p "Would you like to copy any parameters? (y): " COPY
if [ "$COPY" == "y" ]; then 

cat <<'END_TEXT'

Below is a list of Parameters. You can copy all the parameters or individual
parameters based on the parameter name. If encrypted, the KMS key ID is listed as well
and access to the KMS key is required to decrypted and transfer the parameter to the
new account.

END_TEXT

echo "Parameters in source account and KMS key id:"
echo ""

aws ssm describe-parameters \
    --query 'Parameters[*].{Name:Name,KmsKeyId:KeyId}' \
    --output json \
    --profile $ARCHIVE_FROM \
    --region $REGION | jq -r '.[] | [.Name, .KmsKeyId] | @tsv'

echo ""
FROM_PARAMETER="all"
echo ""
echo "Key ARNs and Aliases (one command for all this data: #awswishlist):"
echo ""

aws kms list-aliases --profile $KMS_PROFILE --region $REGION \
    | jq -r --arg region "$REGION" \
    --arg accountid "$(aws sts get-caller-identity --profile $KMS_PROFILE --query Account --output text)" \
    '.Aliases[] | select(.TargetKeyId) | "arn:aws:kms:" + $region + ":" + $accountid + ":key/" + .TargetKeyId + " " + .AliasName'

read -p "Enter KMS key ARN (only, not alias) to use to encrypt parameters in target account: " NEW_KEY_ID

while [[ -n $FROM_PARAMETER ]]; do
   read -p "Enter the parameter name you want to archive or all. Enter to continue: " FROM_PARAMETER
   if [[ -n $FROM_PARAMETER ]]; then
     if [ "$FROM_PARAMETER" == "all" ]; then

         PARAMETERS=$(aws ssm describe-parameters --query 'Parameters[].Name' --output text \
            --profile $ARCHIVE_FROM --region $REGION | tr '\t' '\n')

         for FROM_PARAMETER in $PARAMETERS; do
           TO_ACCOUNT=$(aws sts get-caller-identity --query Account --output text --profile $ARCHIVE_FROM)
           TO_PARAMETER='/archive/'$TO_ACCOUNT''$FROM_PARAMETER

           echo "FROM_PARAMETER: $FROM_PARAMETER"
           echo "TO_PARAMETER: $TO_PARAMETER"
           echo "ARCHIVE_FROM: $ARCHIVE_FROM"
           echo "ARCHIVE_TO: $ARCHIVE_TO"
           echo "REGION: $REGION"
           echo "NEW_KEY_ID: $NEW_KEY_ID"

           if [[ -z "$FROM_PARAMETER" ]]; then echo "FROM_PARAMETER is not set"; exit 1; fi
           if [[ -z "$TO_PARAMETER" ]]; then echo "TO_PARAMETER is not set"; exit 1; fi
           if [[ -z "$ARCHIVE_FROM" ]]; then echo "ARCHIVE_FROM is not set"; exit 1; fi
           if [[ -z "$ARCHIVE_TO" ]]; then echo "ARCHIVE_TO is not set"; exit 1; fi
           if [[ -z "$REGION" ]]; then echo "REGION is not set"; exit 1; fi
           if [[ -z "$NEW_KEY_ID" ]]; then echo "NEW_KEY_ID is not set"; exit 1; fi

           archive_parameter "$FROM_PARAMETER" "$TO_PARAMETER" "$ARCHIVE_FROM" "$ARCHIVE_TO" "$REGION" "$NEW_KEY_ID"
         done
         FROM_PARAMETER=""
     else
       read -p "Enter the parameter name in the destination account:" TO_PARAMETER
       archive_parameter $FROM_PARAMETER $TO_PARAMETER $ARCHIVE_FROM $ARCHIVE_TO $REGION $NEW_KEY_ID
    fi
  fi

done


fi #end if copy
COPY=""

