#!/bin/bash -e
################################################################
#
#  Name: S3 Buckets
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/s3-buckets.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



archive_bucket(){
   FROM_BUCKET="$1"
   TO_BUCKET="$2"
   ARCHIVE_TO="$3"
   REGION="$4"
   NEW_KEY_ID="$5"

   if aws s3api list-buckets --profile "${ARCHIVE_TO}" --region "${REGION}" \
         --query "Buckets[?Name=='${TO_BUCKET}'].Name" --output text | grep -q "${TO_BUCKET}"; then

      echo "Bucket: $TO_BUCKET exists"

   else
      read -p "Bucket: $TO_BUCKET does not exist in the destination account. Do you want to create it?"

      aws s3api create-bucket \
          --bucket "${TO_BUCKET}" \
          --region "${REGION}" \
          --profile "${ARCHIVE_TO}" \
          --create-bucket-configuration LocationConstraint="${REGION}"
   fi

   KEY_ID=$(aws s3api get-bucket-encryption \
      --bucket "${TO_BUCKET}" \
      --profile "${ARCHIVE_TO}" \
      --region "${REGION}")

   #the jq filter has to be on one line apparently or Gemini cannot tell me how to break it up without causing an error.
   KEY_ID=$(echo "${KEY_ID_RAW_OUTPUT}" | jq -r '.ServerSideEncryptionConfiguration.Rules[] | select(.ApplyServerSideEncryptionByDefault.SSEAlgorithm == "aws:kms") | .ApplyServerSideEncryptionByDefault.KMSMasterKeyID')

   echo "KEY_ID on bucket: $KEY_ID"

   if [[ -z "${KEY_ID}" ]]; then

     if [[ -z "$NEW_KEY_ID" ]]; then
       read -p "KMS key ID not found on TO_BUCKET $TO_BUCKET. Enter the ARN or ID of the KMS Key to use for encryption: " NEW_KEY_ID
     fi
     echo "Adding encryption to bucket using key: $NEW_KEY_ID"
     aws s3api put-bucket-encryption \
        --bucket "${TO_BUCKET}" \
        --profile "${ARCHIVE_TO}" \
        --region "${REGION}" \
        --server-side-encryption-configuration '{
        "Rules": [
        {
          "ApplyServerSideEncryptionByDefault": {
            "SSEAlgorithm": "aws:kms",
            "KMSMasterKeyID": "'"${NEW_KEY_ID}"'"
          }
        }
        ]
        }'

   fi

   #we need to use the role in the to account and make sure it has access to the 
   #bucket in the from account and the kms key used to encrypt the data
   aws s3 sync s3://$FROM_BUCKET/ s3://$TO_BUCKET/ \
         --profile $ARCHIVE_TO \
         --region $REGION
}

cat <<'END_TEXT'

***************************
S3 Buckets 
***************************
END_TEXT

read -p "Would you like to copy any S3 buckets? (y): " COPY

if [ "$COPY" == "y" ]; then

read -p "Would you like to see the required IAM, KMS and S3 policies to transfer an encrypted bucket? (y): " V

if [ "$V" == "y" ]; then

cat <<'END_TEXT' 
Add IAM policy for archive admin role in the from_account (limit further if needed):
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::*",
                "arn:aws:s3:::*/*"
            ]
        }
    ]
}

Add bucket policy for each bucket in the from account:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "<AccountA-IAM-ROLE-ARN>" 
            },
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR_BUCKET_NAME",
                "arn:aws:s3:::YOUR_BUCKET_NAME/*"
            ]
        }
    ]
}

If the bucket is encrypted make sure the key policy grants access to the archive admin role.
The permissions need to be added to the keys on buckets in both accounts. In addition,
the role executing the sync command needs KMS permissions in the IAM role policy.

{
    "Version": "2012-10-17",
    "Id": "key-policy-for-s3-role-access",
    "Statement": [
        {
            "Sid": "Allow role to encrypt and decrypt data in S3",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<AWS-ACCOUNT-ID>:role/<ROLE-NAME>"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
            "Resource": "*" 
        }
    ]
}


END_TEXT
fi

read -p "Do you want to see the list of S3 buckets? (y): " VIEW
if [ "$VIEW" == "y" ]; then

cat <<'END_TEXT'

Below is a list of S3 Buckets. You can copy all the buckets or individual
buckets based on the bucket name. You will need permission to use the KMS key 
if one exists to decrypt the contents of the bucket.

END_TEXT

  for BUCKET_NAME in $(aws s3api list-buckets --query "Buckets[].Name" --output text --profile $ARCHIVE_FROM --region $REGION); do 
    echo "Bucket: ${BUCKET_NAME}" 
    ENCRYPTION_INFO=$(aws s3api get-bucket-encryption --bucket "${BUCKET_NAME}" --profile $ARCHIVE_FROM --region $REGION)
    if [[ $? -eq 0 ]]; then 
       KMS_KEY_ID=$(echo "${ENCRYPTION_INFO}" | \
       jq -r '.ServerSideEncryptionConfiguration.Rules[0].ApplyServerSideEncryptionByDefault.KMSMasterKeyID')
    if [ "${KMS_KEY_ID}" == "null" ]; then KMS_KEY_ID=""; fi
    echo "  KMS Key ID: ${KMS_KEY_ID}" 
   fi
  done
  echo ""

fi

FROM_BUCKET="all"
echo ""
echo "Key ARNs and Aliases (one command for all this data: #awswishlist): "
echo ""

aws kms list-aliases --profile $KMS_PROFILE --region $REGION \
    | jq -r --arg region "$REGION" \
    --arg accountid "$(aws sts get-caller-identity --profile $KMS_PROFILE --query Account --output text)" \
    '.Aliases[] | select(.TargetKeyId) | "arn:aws:kms:" + $region + ":" + $accountid + ":key/" + .TargetKeyId + " " + .AliasName'

read -p "Enter KMS key ARN (only, not alias) to use to encrypt buckets in target account: " NEW_KEY_ID

while [[ -n $FROM_BUCKET ]]; do
   read -p "Enter the bucket name you want to archive or all. Enter to continue: " FROM_BUCKET
   if [[ -n $FROM_BUCKET ]]; then
     if [ "$FROM_BUCKET" == "all" ]; then

         BUCKETS=$(aws s3api list-buckets --profile $ARCHIVE_FROM --region $REGION  --query "Buckets[].Name" --output text)
         for FROM_BUCKET in $BUCKETS; do
           TO_BUCKET='archive-'$FROM_BUCKET
           archive_bucket $FROM_BUCKET $TO_BUCKET $ARCHIVE_TO $REGION $NEW_KEY_ID
         done
         FROM_BUCKET=""
     else
       read -p "Enter the bucket to which you want to copy the files in the ARCHIVE_TO account: " TO_BUCKET
       archive_bucket $FROM_BUCKET $TO_BUCKET $ARCHIVE_TO $REGION $NEW_KEY_ID
    fi
  fi
   
done

fi #end copy
COPY=""
