#!/bin/bash -e
################################################################
#
#  Name: Secrets
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/secrets.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




archive_secret(){
 local FROM_SECRET="$1"
 local TO_SECRET="$2"
 local ARCHIVE_FROM="$3"
 local ARCHIVE_TO="$4"
 local REGION="$5"
 local KMS_KEY_ID="$6"

 local SECRET_VALUE=""

 SECRET_VALUE=$(aws secretsmanager get-secret-value \
    --profile "$ARCHIVE_FROM" \
    --region "$REGION" \
    --secret-id "$FROM_SECRET" \
    --query 'SecretString' \
    --output text)
   
    if [ -z "$SECRET_VALUE" ]; then
        echo "Error: Secret value could not be retrieved or is empty."
        exit 1
    fi

    aws secretsmanager create-secret \
    --profile "$ARCHIVE_TO" \
    --region "$REGION" \
    --name "$TO_SECRET" \
    --secret-string "$SECRET_VALUE" \
    --kms-key-id "$KMS_KEY_ID"

    SECRET_VALUE=""
}

cat <<'END_TEXT'

***************************
SSM Secrets
***************************

END_TEXT

read -p "Would you like to copy any secrets? (y): " COPY
if [ "$COPY" == "y" ]; then 

cat <<'END_TEXT'

Below is a list of Secrets Manager secrets. You can copy all the secrets or individual
secrets based on the secret name. If encrypted, the KMS key ID is listed as well
and access to the KMS key is required to decrypted and transfer the secret to the
new account.

END_TEXT

echo "Secrets in source account:"
echo ""
aws secretsmanager list-secrets --query "SecretList[*].[Name, KmsKeyId]" --output text \
 --profile $ARCHIVE_FROM --region $REGION

echo ""
FROM_SECRET="all"
echo ""
echo "Key ARNs and Aliases (one command for all this data: #awswishlist):"
echo ""

aws kms list-aliases --profile $KMS_PROFILE --region $REGION \
    | jq -r --arg region "$REGION" \
    --arg accountid "$(aws sts get-caller-identity --profile $KMS_PROFILE --query Account --output text)" \
    '.Aliases[] | select(.TargetKeyId) | "arn:aws:kms:" + $region + ":" + $accountid + ":key/" + .TargetKeyId + " " + .AliasName'

read -p "Enter KMS key ARN (only, not alias) to use to encrypt secrets in target account: " NEW_KEY_ID

while [[ -n $FROM_SECRET ]]; do
   read -p "Enter the secret name you want to archive or all. Enter to continue: " FROM_SECRET
   if [[ -n $FROM_SECRET ]]; then
     if [ "$FROM_SECRET" == "all" ]; then

         SECRETS=$(aws secretsmanager list-secrets --query 'SecretList[*].Name' --profile $ARCHIVE_FROM --region $REGION --output text)
         for FROM_SECRET in $SECRETS; do
           TO_ACCOUNT=$(aws sts get-caller-identity --query Account --output text --profile $ARCHIVE_FROM)
           TO_SECRET='archive-'$TO_ACCOUNT'-'$FROM_SECRET

           echo "FROM_SECRET: $FROM_SECRET"
           echo "TO_SECRET: $TO_SECRET"
           echo "ARCHIVE_FROM: $ARCHIVE_FROM"
           echo "ARCHIVE_TO: $ARCHIVE_TO"
           echo "REGION: $REGION"
           echo "NEW_KEY_ID: $NEW_KEY_ID"

           if [[ -z "$FROM_SECRET" ]]; then echo "FROM_SECRET is not set"; exit 1; fi
           if [[ -z "$TO_SECRET" ]]; then echo "TO_SECRET is not set"; exit 1; fi
           if [[ -z "$ARCHIVE_FROM" ]]; then echo "ARCHIVE_FROM is not set"; exit 1; fi
           if [[ -z "$ARCHIVE_TO" ]]; then echo "ARCHIVE_TO is not set"; exit 1; fi
           if [[ -z "$REGION" ]]; then echo "REGION is not set"; exit 1; fi
           if [[ -z "$NEW_KEY_ID" ]]; then echo "NEW_KEY_ID is not set"; exit 1; fi

           archive_secret "$FROM_SECRET" "$TO_SECRET" "$ARCHIVE_FROM" "$ARCHIVE_TO" "$REGION" "$NEW_KEY_ID"
         done
         FROM_SECRET=""
     else
       read -p "Enter the secet name in the destination account:" TO_SECRET
       archive_secret $FROM_SECRET $TO_SECRET $ARCHIVE_FROM $ARCHIVE_TO $REGION $NEW_KEY_ID
    fi
  fi

done


fi #end if copy
COPY=""

