#!/bin/bash -e
################################################################
#
#  Name: Test Ami
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/aws-archive-account/scripts/test-ami.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################




cat <<'END_TEXT'

***************************
TEST EC2 AMI (Amamazon Machine Image)
***************************

It takes too long for an AMI to become available 
for the archive script most of the time so 
this separate script can be used to test that a single
AMI is working once it becomes available.

It would be nice if AWS would speed up the AMI
creation process ;-)

AWS CLI profiles in this account:

END_TEXT

aws configure list-profiles

read -p "Enter the profile you want to use: " PROFILE
read -p "Enter the region you want to use: " REGION
read -p "Enter the KMS profile that can list available KMS keys to encrypt the test instance: " KMS_PROFILE

read -p "Do you want to see a list of images in the from account? (y): " VIEW
if [ "$VIEW" == "y" ]; then

cat <<'END_TEXT'
Below is a list of Amazon Machine Images in this account.

END_TEXT

  aws ec2 describe-images \
  --owners self \
  --profile $PROFILE \
  --region $REGION \
  --query 'Images[*].{Name: Name, ImageId: ImageId, Snapshots: BlockDeviceMappings[?Ebs.Encrypted==`true`].Ebs.SnapshotId}' \
  --output json \
 | jq -r '.[] | "\(.Name),\(.ImageId),\(.Snapshots[] // "N/A")" ' \
 | while IFS=, read -r AMI_NAME AMI_ID SNAPSHOT_ID; do
    if [[ "${SNAPSHOT_ID}" == "N/A" ]]; then
        echo "AMI Name: ${AMI_NAME}, AMI ID: ${AMI_ID}, KMS Key ID: No encryption/KMS key used"
    else
        KMS_KEY_ID=$(aws ec2 describe-snapshots \
          --snapshot-ids "${SNAPSHOT_ID}" \
          --profile $PROFILE \
          --region $REGION \
          --query "Snapshots[*].KmsKeyId" \
          --output text 2>/dev/null)
        if [[ -z "${KMS_KEY_ID}" ]]; then
            KMS_KEY_ID="Default/AWS managed key"
        fi
        echo "AMI Name: ${AMI_NAME}, AMI ID: ${AMI_ID}, KMS Key ID: ${KMS_KEY_ID}"
    fi
  done

  echo ""
fi

read -p  "Done displaying image names. Copy AMI id you want to test: " AMI_ID


   echo ""
   echo "EC2 SSH keys in the to account:"
   echo ""
   aws ec2 describe-key-pairs  --query 'KeyPairs[*].KeyName' \
     --profile $PROFILE --region $REGION --output text
   echo ""
   read -p "Enter the name of your SSH key pair or list to see a list of key pairs: " KEY_PAIR
   echo ""
   echo "Security groups in the to account:"
   echo ""
   aws ec2 describe-security-groups --query "SecurityGroups[*].[GroupId,GroupName]" --output text \
      --region $REGION --profile $PROFILE
   echo ""
   read -p "Enter the Security Group ID (e.g., sg-xxxxxxxxxxxxxxxxx): " SG_ID
   echo ""
   echo "Subnets in the to account:"
   aws ec2 describe-subnets --profile $PROFILE --region $REGION \
      --query "Subnets[*].{ID:SubnetId,Name:Tags[?Key=='Name']|[0].Value}" --output text
   echo ""
   read -p "Enter the Subnet ID (e.g., subnet-xxxxxxxxxxxxxxxxx): " SUBNET_ID
   echo ""
   echo "Key ARNs and Aliases (one command for all this data: #awswishlist):"
   echo ""

   aws kms list-aliases --profile $KMS_PROFILE --region $REGION \
    | jq -r --arg region "$REGION" \
    --arg accountid "$(aws sts get-caller-identity --profile $KMS_PROFILE --query Account --output text)" \
    '.Aliases[] | select(.TargetKeyId) | "arn:aws:kms:" + $region + ":" + $accountid + ":key/" + .TargetKeyId + " " + .AliasName'

   echo ""  
   read -p "Enter the KMS Key ARN for EBS encryption in the destination account: " KMS_KEY
        
   read -p "Do you want to see valid instances types for this ami? (y): " SHOW
   if [ "$SHOW" == "y" ]; then

       aws ec2 describe-instance-types \
       --filters "Name=processor-info.supported-architecture,\
       Values=$(aws ec2 describe-images --image-ids "$AMI_ID" \
       --query 'Images[0].Architecture' --output text \
       --profile "$PROFILE")" --query 'InstanceTypes[*].InstanceType' \
       --output json --region $REGION --profile "$PROFILE" | jq -r '.[]'

       echo ""
   fi

   read -p "Enter desired image type (e.g., t2.micro, t2.medium): " INSTANCE_TYPE

   BLOCK_DEVICE_MAPPINGS='[{"DeviceName": "/dev/xvda","Ebs": {"Encrypted": true, "KmsKeyId": "'$KMS_KEY'"}}]'
   echo "BLOCK_DEVICE_MAPPINGS: $BLOCK_DEVICE_MAPPINGS"

   echo "Launching instance..."

   aws ec2 run-instances --image-id "$AMI_ID" \
    --instance-type "$INSTANCE_TYPE" --key-name "$KEY_PAIR" \
    --security-group-ids "$SG_ID" \
    --subnet-id "$SUBNET_ID" \
    --block-device-mappings "$BLOCK_DEVICE_MAPPINGS" \
    --output text \
    --region $REGION \
    --profile "$PROFILE"

   echo "Instance launched. Wait for the instance to become available to ensure it works and test access as needed."

