#!/bin/bash -e
################################################################
#
#  Name: Run
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/select-aws-cli-profile/run.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



    PROFILES=($(aws configure list-profiles --no-cli-pager --color off))

    if [ ${#PROFILES[@]} -eq 0 ]; then
        echo "No AWS profiles found."
        exit 1
    fi

    echo "Available AWS profiles:"
    for I in "${!PROFILES[@]}"; do
        echo "$((I+1)). ${PROFILES[I]}"
    done

    while true; do
        read -p "Enter profile number (1-${#PROFILES[@]}): " CHOICE
        if [[ "$CHOICE" =~ ^[0-9]+$ ]] && [ "$CHOICE" -ge 1 ] && [ "$CHOICE" -le ${#PROFILES[@]} ]; then
            PROFILE="${PROFILES[$((CHOICE-1))]}"
            echo "Selected profile: $PROFILE"
            break
        else
            echo "Invalid selection. Please enter a number between 1 and ${#PROFILES[@]}."
        fi
    done

    REGION=$(aws configure get region --profile "$PROFILE" --no-cli-pager --color off)
    if [[ ! "$REGION" =~ ^[a-z]{2}-[a-z]{4}-[0-9]$ ]]; then
        echo "Warning: Profile '$PROFILE' does not have a valid region configured."
        echo "Expected format: xx-xxxx-x (e.g., us-east-1)"
        echo "To fix: aws configure set region us-east-1 --profile $PROFILE"
        exit 1
    fi

    OUTPUT=$(aws configure get output --profile "$PROFILE" --no-cli-pager --color off)
    if [[ -n "$OUTPUT" && ! "$OUTPUT" =~ ^(json|text|table|yaml|yaml-stream)$ ]]; then
        echo "Warning: Profile '$PROFILE' has invalid output format: $OUTPUT"
        echo "Allowed values: json, text, table, yaml, yaml-stream"
        echo "To fix: aws configure set output json --profile $PROFILE"
        exit 1
    fi

    aws sts get-caller-identity --profile "$PROFILE" --no-cli-pager --color off || exit 1
