#!/bin/bash -e
################################################################
#
#  Name: Run
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/view-cloudtrail-errors/run.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



echo "AWS CLI profiles:"
aws configure list-profiles
echo ""
read -p "enter profile: " PROFILE
read -p "enter region: " REGION
read -p "enter how many minutes you want to retrieve (e.g. 5 or 10): " MINUTES

# On Linux
START_TIME=$(date -u --date "$MINUTES minutes ago" '+%Y-%m-%dT%H:%M:%SZ')
# On a Mac, per Michael Speer, Xpertloop (I haven't tested this as I do not install the AWS CLI locally)
#START_TIME=$(date -u -v-${MINUTES}M'+%Y%m-$dT%H:%M:%SZ')

echo ""
echo "CLOUDTRAIL ERRORS ONLY"
echo ""
aws cloudtrail lookup-events \
    --start-time "$START_TIME" \
    --profile $PROFILE \
    --region $REGION \
    --color off \
    --output json | jq '.Events[] | select(.CloudTrailEvent | fromjson.errorCode) | .CloudTrailEvent |= fromjson'
