#!/bin/bash -e
################################################################
#
#  Name: Install Amazon Q
#  GitHub repository: https://github.com/2ndSightLab
#  File: install_amazon_q.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Install Amazon Q on EC2 instance
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    echo "Cannot detect OS"
    exit 1
fi

# Install Amazon Q based on OS
case $OS in
    "ubuntu")
        apt-get update
        curl -sSL https://aws-dev-tools-downloads.s3.us-east-1.amazonaws.com/amazon-q/latest/linux/amd64/amazon-q-linux-amd64.tar.gz -o /tmp/amazon-q.tar.gz
        tar -xzf /tmp/amazon-q.tar.gz -C /tmp/
        mv /tmp/q /usr/local/bin/
        chmod +x /usr/local/bin/q
        ;;
    "amzn"|"rhel"|"centos")
        yum update -y
        curl -sSL https://aws-dev-tools-downloads.s3.us-east-1.amazonaws.com/amazon-q/latest/linux/amd64/amazon-q-linux-amd64.tar.gz -o /tmp/amazon-q.tar.gz
        tar -xzf /tmp/amazon-q.tar.gz -C /tmp/
        mv /tmp/q /usr/local/bin/
        chmod +x /usr/local/bin/q
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

# Verify installation
/usr/local/bin/q --version
