#!/bin/bash -e
################################################################
#
#  Name: Install Rust
#  GitHub repository: https://github.com/2ndSightLab
#  File: install_rust.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Install Rust and Cargo on EC2 instance
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################

sudo -u ec2-user bash << 'EOF'

sudo yum install glibc-devel
sudo yum install gcc glibc-devel -y

# Install Rust using rustup (official installer)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Source the cargo environment
source ~/.cargo/env

# Update to latest stable
rustup update stable
rustup default stable

# Add to ec2-user's bashrc
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc

# Verify installation
rustc --version
cargo --version

EOF

# Add cargo to PATH for all users if it doesn't already exist
if [[ ! -f /etc/profile.d/rust.sh ]] || ! grep -q 'export PATH="$HOME/.cargo/bin:$PATH"' /etc/profile.d/rust.sh; then
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' | sudo tee -a /etc/profile.d/rust.sh
fi

echo $PATH

sudo chmod +x /etc/profile.d/rust.sh

# Add to ec2-user's bashrc as well (in case profile.d doesn't work)
grep -qF 'export PATH="$HOME/.cargo/bin:$PATH"' ~/.bashrc || echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc

# Source bashrc to make Rust available immediately
sudo -u ec2-user bash -c 'source /home/ec2-user/.bashrc'

cargo install cargo-audit --locked
