AWSTemplateFormatVersion: "2010-09-09"
Description: "My API Gateway and Lambda function"

Parameters:

  lambdaFunctionName:
    Type: "String"

  SecretParameter:
    Type: "String"
    NoEcho: true

  KeyId:
    Type: "String"

Resources:

  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: lab-3-3-secret
      Description: Secret for 2SL3000 Lab-3-3
      SecretString: !Ref SecretParameter

  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "2sl-3000-api-secrets"
      Description: "API Name"

  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    DependsOn:
      - lambdaApiGatewayInvoke
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "lambdaFunction.Arn"
      ResourceId: !GetAtt "apiGateway.RootResourceId"
      RestApiId: !Ref "apiGateway"

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "apiGateway"
      StageName: "secretmanager"

  lambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          import os
          import boto3
          def handler(event,context):
            client=boto3.client("secretsmanager")
            response=client.get_secret_value(SecretId='lab-3-3-secret')
            bodyrepsonse = "Secret from AWS Secrets Manager: {}".format(response['SecretString'])
            return {
              'body': bodyrepsonse,
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }
      Description: "Lambda function lab 3.3"
      Handler: "index.handler"
      FunctionName: !Ref lambdaFunctionName
      MemorySize: 128
      Role: !GetAtt "lambdaIAMRole.Arn"
      Runtime: "python2.7"
      Timeout: 10

  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - lambdaFunction
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "lambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/POST/"

  lambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaFunctionName}:*"
              - Action:
                  - "ssm:DescribeParameters"
                Effect: Allow
                Resource: "*"
              - Action:
                  - "SecretsManager:GetSecretValue"
                Effect: "Allow"
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:lab-3-3-*
              - Action:
                  - "ssm:GetParameters"
                Effect: "Allow"
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lab-3-3-*
              - Action:
                  - "kms:Decrypt"
                Effect: Allow
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KeyId}
          PolicyName: "lambda"

  lambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${lambdaFunctionName}"
      RetentionInDays: 90

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub "https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/secretmanager"

  lambdaArn:
    Value: !GetAtt "lambdaFunction.Arn"
