#####################################################################################################
# Copyright Notice
# All Rights Reserved.
# All course materials (the “Materials”) are protected by copyright under U.S. Copyright laws 
# and are the property of 2nd Sight Lab. They are provided pursuant to a royalty free, 
# perpetual license to the course attendee (the "Attendee") to whom they were presented by 
# 2nd Sight Lab and are solely for the training and education of the Attendee. The Materials 
# may not be copied, reproduced, distributed, offered for sale, published, displayed, performed, 
# modified, used to create derivative works, transmitted to others, or used or exploited in any way, 
# including, in whole or in part, as training materials by or for any third party.

# The above copyright notice and this permission notice shall be included in all copies or 
# substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES 
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#####################################################################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: "PFSense Cloud VPC"

Parameters: 
  VPCName:
    Description: The name of this VPC. All resources will be tagged with this name.
    Type: String
    Default: 2SL-3000-PFSENSE-VPC
  VPCCidr:
    Description: |
      VPC CIDR Block. Please make sure to make this CIDR large enough to support 
      multiple subnets. The allowed sizes are from a /16 to a /28. We will be 
      deploying 2 subnets, so plan accordingly.
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
  Username:
    Description: Your username for taggging resources.
    Type: String

Resources: 
  # ------------------------------------------------
  # Flow Logs Setup
  # ------------------------------------------------
  FlowLogIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: vpc-flow-logs.amazonaws.com
          Sid: ""
        Version: 2012-10-17
  FlowLogIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
          - logs:PutLogEvents
          Effect: Allow
          Resource: "*"
        Version: "2012-10-17"
      PolicyName: VPC_FLOW_LOGS
      Roles:
      - !Ref FlowLogIamRole
  # ------------------------------------------------
  # VPC Setup
  # ------------------------------------------------
  BaseVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref VPCCidr
      Tags:
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
  BaseVPCDHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers: 
      - AmazonProvidedDNS
      NtpServers:
      - 169.254.169.123
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-DHCPOptions
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCDHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: !Sub ${BaseVPCDHCPOptions}
      VpcId: !Sub ${BaseVPC}
  BaseVPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId: !Sub ${BaseVPC}
      DeliverLogsPermissionArn: !GetAtt FlowLogIamRole.Arn
      LogGroupName: !Sub ${VPCName}-FlowLogsGroup
      ResourceType: VPC
      TrafficType: ALL
  BaseVPCInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-InternetGateway
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCInternetGatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Sub ${BaseVPC}
      InternetGatewayId: !Sub ${BaseVPCInternetGateway}
  # ------------------------------------------------
  # Public Subnet Setup
  # ------------------------------------------------
  BaseVPCPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        !Select 
          - 0
          - !GetAZs
            Ref: 'AWS::Region'
      VpcId: !Sub ${BaseVPC}
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt BaseVPC.CidrBlock, 16, 8 ] ]
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-PublicSubnet1
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Sub ${BaseVPC}
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-Public-RouteTable
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCPublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Sub ${BaseVPCPublicSubnet}
      RouteTableId: !Sub ${BaseVPCPublicRouteTable}
  BaseVPCPublicDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Sub ${BaseVPCPublicRouteTable}
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Sub ${BaseVPCInternetGateway}
  # ------------------------------------------------
  # Private Subnet Setup
  # ------------------------------------------------
  BaseVPCPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        !Select 
          - 0
          - !GetAZs
            Ref: 'AWS::Region'
      VpcId: !Sub ${BaseVPC}
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt BaseVPC.CidrBlock, 16, 8 ] ]
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-PrivateSubnet
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Sub ${BaseVPC}
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-Private-RouteTable
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCPrivate1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Sub ${BaseVPCPrivateSubnet}
      RouteTableId: !Sub ${BaseVPCPrivateRouteTable}
  # ------------------------------------------------
  # Network ACL
  # ------------------------------------------------
  BaseVPCPublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Sub ${BaseVPC}
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-Public-NACL
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  BaseVPCPublicNACLAssociation1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref BaseVPCPublicSubnet
      NetworkAclId: !Ref BaseVPCPublicNACL
  BaseVPCPrivateNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Sub ${BaseVPC}
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-Application-NACL
      - Key: StackName
        Value: !Sub ${AWS::StackName}
      - Key: VPC_Name
        Value: !Sub ${VPCName}
      - Key: Created_By
        Value: !Sub ${Username}
  ApplicationNACLAssociation1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref BaseVPCPrivateSubnet
      NetworkAclId: !Ref BaseVPCPrivateNACL

Outputs:
  BaseVPCId:
    Description: The Base VPC ID
    Value: !Sub ${BaseVPC}
    Export:
      Name: "PFSense-VPCID"
  BaseVPCPublicSubnetId:
    Description: Public Subnet ID
    Value: !Sub ${BaseVPCPublicSubnet}
    Export:
      Name: "PFSense-PublicSubnetID"
  BaseVPCPrivateSubnetId:
    Description: Public Subnet ID
    Value: !Sub ${BaseVPCPrivateSubnet}
    Export:
      Name: "PFSense-PrivateSubnetID"
  BaseVPCPublicRouteTableId:
    Description: Public Subnets Route Table ID
    Value: !Sub ${BaseVPCPublicRouteTable}
    Export:
      Name: "PFSense-PublicRouteTableID"
  BaseVPCPrivateRouteTableId:
    Description: Public Subnets Route Table ID
    Value: !Sub ${BaseVPCPrivateRouteTable}
    Export:
      Name: "PFSense-PrivateRouteTableID"
  BaseVPCPublicNACLId:
    Description: Public Subnets NACL ID
    Value: !Sub ${BaseVPCPublicNACL}
    Export:
      Name: "PFSense-PublicNACLID"
  BaseVPCPrivateNACLId:
    Description: Private Subnets NACL ID
    Value: !Sub ${BaseVPCPrivateNACL}
    Export:
      Name: "PFSense-PrivateNACLID"
  BaseVPCCidr:
    Description: VPC Base CIDR
    Value: !Sub ${VPCCidr}
    Export:
      Name: "PFSense-VPCCidr"
  BaseVPCPublicCidr:
    Description: VPC Public Subnet Cidr
    Value: !Select [ 0, !Cidr [ !GetAtt BaseVPC.CidrBlock, 16, 8 ] ]
    Export:
      Name: "PFSense-PublicCidr"
  BaseVPCPrivateCidr:
    Description: VPC Private Subnet Cidr
    Value: !Select [ 1, !Cidr [ !GetAtt BaseVPC.CidrBlock, 16, 8 ] ]
    Export:
      Name: "PFSense-PrivateCidr"
  VPCName:
    Description: VPC Name
    Value: !Sub ${VPCName}
    Export:
      Name: "PFSense-VPCName"