#####################################################################################################
# Copyright Notice
# All Rights Reserved.
# All course materials (the “Materials”) are protected by copyright under U.S. Copyright laws 
# and are the property of 2nd Sight Lab. They are provided pursuant to a royalty free, 
# perpetual license to the course attendee (the "Attendee") to whom they were presented by 
# 2nd Sight Lab and are solely for the training and education of the Attendee. The Materials 
# may not be copied, reproduced, distributed, offered for sale, published, displayed, performed, 
# modified, used to create derivative works, transmitted to others, or used or exploited in any way, 
# including, in whole or in part, as training materials by or for any third party.

# The above copyright notice and this permission notice shall be included in all copies or 
# substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES 
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#####################################################################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: "PFSense Cloud NACLs"

Parameters: 
  ManagmentIPAddress:
    Description: Management IP for resources -- your public IP
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Resources:
  # ------------------------------------------------
  # Ingress NACLs - Public
  # ------------------------------------------------
  # Management
  PublicNACLInbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "443"
        To: "443"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  # Needed for VPN
  PublicNACLInbound200Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "200"
      Protocol: "17"
      PortRange:
        From: "500"
        To: "500"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound201Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "201"
      Protocol: "6"
      PortRange:
        From: "500"
        To: "500"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound202Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "202"
      Protocol: "17"
      PortRange:
        From: "4500"
        To: "4500"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound203Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "203"
      Protocol: "6"
      PortRange:
        From: "4500"
        To: "4500"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  # For AWS NTP Server
  PublicNACLInbound300Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "300"
      Protocol: "17"
      PortRange:
        From: "123"
        To: "123"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 169.254.169.123/32
  # Ephemeral Ports
  PublicNACLInbound600Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "600"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound601Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "601"
      Protocol: "17"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
  PublicNACLInbound1000Deny:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "602"
      Protocol: "17"
      PortRange:
        From: "443"
        To: "443"
      RuleAction: Deny
      Egress: "false"
      CidrBlock: !ImportValue "PFSense-PrivateCidr"
  # ------------------------------------------------
  # Egress NACLs - Public
  # ------------------------------------------------
  PublicNACLOutbound100Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "100"
      Protocol: "6"
      PortRange:
        From: "443"
        To: "443"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound101Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "101"
      Protocol: "6"
      PortRange:
        From: "80"
        To: "80"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound102Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "102"
      Protocol: "6"
      PortRange:
        From: "53"
        To: "53"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound103Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "103"
      Protocol: "17"
      PortRange:
        From: "53"
        To: "53"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound104Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "104"
      Protocol: "17"
      PortRange:
        From: "123"
        To: "123"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 169.254.169.123/32
  PublicNACLOutbound200Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "200"
      Protocol: "17"
      PortRange:
        From: "500"
        To: "500"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound201Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "201"
      Protocol: "6"
      PortRange:
        From: "500"
        To: "500"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound202Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "202"
      Protocol: "17"
      PortRange:
        From: "4500"
        To: "4500"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound203Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "203"
      Protocol: "6"
      PortRange:
        From: "4500"
        To: "4500"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  # Ephemeral Ports
  PublicNACLOutbound600Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "600"
      Protocol: "6"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound601Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "601"
      Protocol: "17"
      PortRange:
        From: "1024"
        To: "65535"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
  PublicNACLOutbound1000Allow:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !ImportValue PFSense-PublicNACLID
      RuleNumber: "1000"
      Protocol: "-1"
      RuleAction: Allow
      Egress: "true"
      CidrBlock: !Sub ${ManagmentIPAddress}