#!/bin/bash -e
################################################################
#
#  Name: Run
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/create-q-cli-agent-with-global-context/run.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  AWS automation script
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################



while true; do
    read -p "Enter agent name (letters, numbers, hyphens only): " agent_name
    if [[ "$agent_name" =~ ^[a-zA-Z0-9-]+$ ]] && [[ ${#agent_name} -gt 0 ]]; then
        break
    else
        echo "Invalid name. Use only letters, numbers, and hyphens."
    fi
done

mkdir -p ~/.myagents

echo "Enter rules for your agent (press Enter twice when done):"
rules=""
while IFS= read -r line; do
    if [[ -z "$line" ]]; then
        break
    fi
    rules+="$line"$'\n'
done

cat > ~/.myagents/${agent_name}.md << EOF
# Global Context

## System Information
- OS: Linux
- Current Directory: /home/ec2-user/foxy/aws-scripts/scripts/create-q-cli-agent
- User Type: Hacker/Developer

## Agent Rules
${rules}
EOF

mkdir -p ~/.aws/amazonq/cli-agents

cat > ~/.aws/amazonq/cli-agents/${agent_name}.json << EOF
{
  "\$schema": "https://raw.githubusercontent.com/aws/amazon-q-developer-cli/refs/heads/main/schemas/agent-v1.json",
  "name": "${agent_name}",
  "description": "General purpose Q CLI agent with custom global context and default Q CLI context",
  "prompt": null,
  "mcpServers": {},
  "tools": [
    "fs_read",
    "fs_write",
    "execute_bash",
    "use_aws",
    "gh_issue",
    "knowledge",
    "thinking",
    "todo_list",
    "@mcp_server_name/mcp_tool_name",
    "@mcp_server_name_without_tool_specification_to_include_all_tools"
  ],
  "toolAliases": {},
  "allowedTools": [],
  "resources": [
    "file://$HOME/.myagents/${agent_name}.md",
    "file://AmazonQ.md",
    "file://AGENTS.md",
    "file://README.md",
    "file://.amazonq/rules/**/*.md"
  ],
  "hooks": {},
  "toolsSettings": {
    "execute_bash": {
      "autoAllowReadonly": true
    }
  },
  "useLegacyMcpJson": true,
  "model": null
}
EOF

echo "Agent '${agent_name}' created with global context."
echo ""
echo "Context file written to: ~/.myagents/${agent_name}.md"
echo ""
echo "Current rules in the file:"
echo "========================="
cat ~/.myagents/${agent_name}.md
echo "========================="
echo ""
echo "To update the agent's context, edit the file: ~/.myagents/${agent_name}.md"
echo "Add new rules under the 'Agent Rules' section."
echo ""
echo "1. Launch a chat session with your custom agent (from terminal, not within q chat):"
echo "   q chat --agent ${agent_name}"
echo ""
echo "2. The context from ~/.myagents/${agent_name}.md will be available to the agent"
echo ""
echo "3. Use any Q CLI commands or ask questions - the agent will use your global context"
